# -*- coding: utf-8 -*-
line_style = dict(
activedash = None,
activefill = "blue",#Line color to use when the mouse pointer is moved over the item, if different from fill. 
activestipple = None,
activewidth = 0.0,   #Default is 0.0.
arrow = None,        #Default is NONE.
arrowshape = "8 10 3", #Default is  “8 10 3”.
capstyle = "round",     #Default is BUTT.
dash = None,    #Dash pattern, given as a list of segment lengths. Only the odd segments are drawn.
dashoffset = 0, #Default is 0.
disableddash = None,
disabledfill = "",      #Line color to use when the item is disabled, if different from fill. 
disabledstipple = None,
disabledwidth = 0.0,    #Default is 0.0.
fill = "black",         #Line color. Default is “black”.
joinstyle = "round",    #Default is ROUND.
offset = "0,0",         #Default is “0,0”.
smooth = 0,             #Default is 0.
splinesteps = 12,       #Default is 12.
state = "normal",       #Item state. One of NORMAL, DISABLED, or HIDDEN.
stipple = None,         #Stipple pattern.
tags = None,            #A tag to attach to this item, or a tuple containing multiple tags.
width = 10.0)             #Default is 1.0.
