# -*- coding: utf-8 -*-

level_style = dict(
activedash = None,
activefill = "blue",#Line color to use when the mouse pointer is moved over the item, if different from fill. 
activestipple = None,
activewidth = 0.0,   #Default is 0.0.
arrow = None,        #Default is NONE.
arrowshape = "8 10 3", #Default is  “8 10 3”.
capstyle = "round",     #Default is BUTT.
dash = None,    #Dash pattern, given as a list of segment lengths. Only the odd segments are drawn.
dashoffset = 0, #Default is 0.
disableddash = None,
disabledfill = "",      #Line color to use when the item is disabled, if different from fill. 
disabledstipple = None,
disabledwidth = 0.0,    #Default is 0.0.
fill = "gray",         #Line color. Default is “black”.
joinstyle = "round",    #Default is ROUND.
offset = "0,0",         #Default is “0,0”.
smooth = 0,             #Default is 0.
splinesteps = 12,       #Default is 12.
state = "normal",       #Item state. One of NORMAL, DISABLED, or HIDDEN.
stipple = None,         #Stipple pattern.
tags = None,            #A tag to attach to this item, or a tuple containing multiple tags.
width = 1.0)           #Default is 1.0.

circle_level_style = dict(
activedash = None,
activefill = "",        #Line color to use when the mouse pointer is moved over the item, if different from fill. 
activestipple = None,
activeoutline = "blue",
activewidth = 0.0,      #Default is 0.0.
dash = None,            #Dash pattern, given as a list of segment lengths. Only the odd segments are drawn.
dashoffset = 0,         #Default is 0.
disableddash = None,
disabledfill = "",      #Line color to use when the item is disabled, if different from fill. 
disabledstipple = None,
disabledoutline = None,
disabledoutlinestipple = None,
disabledwidth = 0.0,    #Default is 0.0.
fill = "",              #Line color. Default is “black”.
offset = "0,0",         #Default is “0,0”.
outline = "gray",       #Outline color. Default is “black”.
outlineoffset = "0,0",  #Default is “0,0”.
outlinestipple = None,  #Outline stipple pattern.
state = "normal",       #Item state. One of NORMAL, DISABLED, or HIDDEN.
stipple = None,         #Stipple pattern.
tags = None,            #A tag to attach to this item, or a tuple containing multiple tags.
width = 1.0)            #Default is 1.0.

line_style = dict(
activedash = None,
activefill = "blue",    #Line color to use when the mouse pointer is moved over the item, if different from fill. 
activestipple = None,
activewidth = 0.0,      #Default is 0.0.
arrow = None,           #Default is NONE.
arrowshape = "8 10 3",  #Default is  “8 10 3”.
capstyle = "round",     #Default is BUTT.
dash = None,            #Dash pattern, given as a list of segment lengths. Only the odd segments are drawn.
dashoffset = 0,         #Default is 0.
disableddash = None,
disabledfill = "",      #Line color to use when the item is disabled, if different from fill. 
disabledstipple = None,
disabledwidth = 0.0,    #Default is 0.0.
fill = "black",         #Line color. Default is “black”.
joinstyle = "round",    #Default is ROUND.
offset = "0,0",         #Default is “0,0”.
smooth = 0,             #Default is 0.
splinesteps = 12,       #Default is 12.
state = "normal",       #Item state. One of NORMAL, DISABLED, or HIDDEN.
stipple = None,         #Stipple pattern.
tags = None,            #A tag to attach to this item, or a tuple containing multiple tags.
width = 1.0)            #Default is 1.0.


point_style = dict(
activedash=None,
activefill="red",   #Fill color to use when the mouse pointer is moved over the item, if different from fill. 
activeoutline="black", 
activeoutlinestipple=None,
activestipple=None,
activewidth=2.0,    #Default is 0.0.
dash=None,          #Outline dash pattern, given as a list of segment lengths. Only the odd segments are drawn.
dashoffset=0,       #Default is 0.
disableddash=None,
disabledfill="",    #Fill color to use when the item is disabled, if different from fill. 
disabledoutline="",
disabledoutlinestipple=None,
disabledstipple=None,
disabledwidth=0,    #Default is 0.
fill="",            #Fill color. An empty string means transparent.
offset="0,0",       #Default is “0,0”.
outline="black",    #Outline color. Default is “black”.
outlineoffset="0,0",#Default is “0,0”.
outlinestipple=None,#Outline stipple pattern.
state="normal",     #Item state. One of NORMAL, DISABLED, or HIDDEN.
stipple=None,       #Stipple pattern.
tags=None,          #A tag to attach to this item, or a tuple containing multiple tags.
width=1.0)          #Default is 1.0.


selection_style = dict(
activedash=(20,20),
activefill="",   #Fill color to use when the mouse pointer is moved over the item, if different from fill. 
activeoutline="red", 
activeoutlinestipple=None,
activestipple=None,
activewidth=2.0,    #Default is 0.0.
dash=(20,20),          #Outline dash pattern, given as a list of segment lengths. Only the odd segments are drawn.
dashoffset=0,       #Default is 0.
disableddash=None,
disabledfill="",    #Fill color to use when the item is disabled, if different from fill. 
disabledoutline="",
disabledoutlinestipple=None,
disabledstipple=None,
disabledwidth=0,    #Default is 0.
fill="",            #Fill color. An empty string means transparent.
offset="0,0",       #Default is “0,0”.
outline="gray",    #Outline color. Default is “black”.
outlineoffset="0,0",#Default is “0,0”.
outlinestipple=None,#Outline stipple pattern.
state="normal",     #Item state. One of NORMAL, DISABLED, or HIDDEN.
stipple=None,       #Stipple pattern.
tags=None,          #A tag to attach to this item, or a tuple containing multiple tags.
width=2.0)          #Default is 1.0.

polygon_style = dict(
activedash=(10,10),
activefill="",       #Fill color to use when the mouse pointer is moved over the item, if different from fill. 
activeoutline="red", 
activeoutlinestipple=None,
activestipple=None,
activewidth=0.0,        #Default is 0.0.
dash=(10,10),              #Outline dash pattern, given as a list of segment lengths. Only the odd segments are drawn.
dashoffset=0,           #Default is 0.
disableddash=None,
disabledfill=None,      #Fill color to use when the item is disabled, if different from fill. 
disabledoutline=None,
disabledoutlinestipple=None,
disabledstipple=None,
disabledwidth=0.0,      #Default is 0.0.
fill="",                #Fill color. Default is “black”.
joinstyle="round",      #Default is ROUND.
offset="0,0",             #Default is “0,0”.
outline="black",        #Outline color.
outlineoffset="0,0",      #Default is “0,0”.
outlinestipple=None,    #Outline stipple pattern.
smooth=0,               #Default is 0.
splinesteps=12,         #Default is 12.
state="normal",         #Item state. One of NORMAL, DISABLED, or HIDDEN.
stipple=None,           #Stipple pattern.
tags=None,              #A tag to attach to this item, or a tuple containing multiple tags.
width=2.0)              #Default is 1.0.
